import Head from "next/head";
import Image from "next/image";
import React, { Dispatch, useState } from "react";
import Header from "../header/Header";

export interface AppStateContext {
    theme?: "dark" | "light";
    setAppState?: Dispatch<AppStateContext>;
    onChangeState?: (
        key: keyof AppStateContext,
        value: AppStateContext[keyof AppStateContext]
    ) => void;
}

export const AppStateContext = React.createContext<AppStateContext>({});

export interface ILayoutProps {
    children: any;
}

const Layout: React.FC<ILayoutProps> = ({ children }) => {
    const [appState, setAppState] = useState<AppStateContext>({
        theme: "dark",
    });

    const { theme } = appState || {};

    const onChangeState = (key: keyof AppStateContext, value: any) => {
        setAppState((prev) => ({ ...prev, [key]: value }));
    };

    const renderMetaHead = () => (
        <Head>
            <title>Do Xuan Trung</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );

    return (
        <AppStateContext.Provider value={{ theme, setAppState, onChangeState }}>
            {renderMetaHead()}
            <div className="mx-3 md:mx-20 lg:mx-40">
                <Header />
                <main>{children}</main>;
                <footer className="pt-10 pb-5 text-center">
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex flex-row items-center mx-auto"
                    >
                        <text className="inline-flex dark:text-white">
                            Powered by{" "}
                        </text>
                        <span className="ml-3">
                            <Image
                                src="/favicon.ico"
                                alt="Vercel Logo"
                                height={30}
                                width={30}
                                layout="fixed"
                            />
                        </span>
                    </a>
                </footer>
            </div>
        </AppStateContext.Provider>
    );
};

export default Layout;
