import Head from "next/head";
import Image from "next/image";
import React, { Dispatch, useState } from "react";

export interface AppStateContext {
    theme?: "dark" | "light";
    setAppState?: Dispatch<AppStateContext>;
    onChangeState?: (
        key: keyof AppStateContext,
        value: AppStateContext[keyof AppStateContext]
    ) => void;
}

export const AppStateContext = React.createContext<AppStateContext>({});

export interface ILayoutProps {
    children: any;
}

const Layout: React.FC<ILayoutProps> = ({ children }) => {
    const [appState, setAppState] = useState<AppStateContext>({
        theme: "dark",
    });

    const { theme } = appState || {};

    const onChangeState = (key: keyof AppStateContext, value: any) => {
        setAppState((prev) => ({ ...prev, [key]: value }));
    };

    return (
        <AppStateContext.Provider value={{ theme, setAppState, onChangeState }}>
            <Head>
                <title>Do Xuan Trung</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>{children}</div>;
            <footer className="px-5 pt-10 pb-5 text-center">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex flex-row items-center mx-auto"
                >
                    <text className="inline-flex dark:text-white">
                        Powered by{" "}
                    </text>
                    <span className="">
                        <Image
                            src="/favicon.ico"
                            alt="Vercel Logo"
                            height={30}
                            width={30}
                            layout="fixed"
                        />
                    </span>
                </a>
            </footer>
        </AppStateContext.Provider>
    );
};

export default Layout;
