import Head from "next/head";
import Image from "next/image";
import React, { Dispatch, useState } from "react";
import Header from "../header/Header";

export interface AppStateContext {
    theme?: "dark" | "light";
    setAppState?: Dispatch<AppStateContext>;
    onChangeState?: (
        key: keyof AppStateContext,
        value: AppStateContext[keyof AppStateContext]
    ) => void;
}

export const AppStateContext = React.createContext<AppStateContext>({});

export interface ILayoutProps {
    children: any;
}

const Layout: React.FC<ILayoutProps> = ({ children }) => {
    const [appState, setAppState] = useState<AppStateContext>({
        theme: "dark",
    });

    const { theme } = appState || {};

    const onChangeState = (key: keyof AppStateContext, value: any) => {
        setAppState((prev) => ({ ...prev, [key]: value }));
    };

    const renderMetaHead = () => (
        <Head>
            <title>Do Xuan Trung</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );

    return (
        <AppStateContext.Provider value={{ theme, setAppState, onChangeState }}>
            {renderMetaHead()}
            <div className="mx-3 md:mx-20 lg:mx-30 xl:mx-40 min-h-screen flex flex-col">
                <Header />
                <main className="h-full flex-grow">{children}</main>
            </div>
        </AppStateContext.Provider>
    );
};

export default Layout;
