import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { BsMoonStarsFill, BsGithub, BsLinkedin } from "react-icons/bs";
import { AiFillGitlab } from "react-icons/ai";
import styles from "../styles/Home.module.css";

declare const VALID_LAYOUT_VALUES: readonly [
    "fill",
    "fixed",
    "intrinsic",
    "responsive",
    undefined
];

const type: typeof VALID_LAYOUT_VALUES[number] = "fill";

const Home: NextPage = () => {
    const renderHeader = () => {
        return (
            <section className="flex flex-row items-center w-ful justify-between py-10">
                <h4 className="text-2xl ">Developer</h4>
                <div className="flex flex-row items-center">
                    <Link className="" href={"./"}>
                        <div className="mr-5 cursor-pointer hover:text-blue-500">
                            Projects
                        </div>
                    </Link>
                    <Link className="" href={"./"}>
                        <div className="cursor-pointer hover:text-blue-500">
                            Resume
                        </div>
                    </Link>
                    <BsMoonStarsFill className="ml-5" color="white" size={24} />
                </div>
            </section>
        );
    };

    const renderBody = () => {
        return (
            <div className="">
                <section className="mx-auto">
                    <div className="relative bg-gradient-to-b from-blue-500 rounded-full w-80 h-80 mx-auto mt-20">
                        <Image
                            src={require("../../public/images/dev-ed-wave.png")}
                            alt="avatar"
                            // layout="fixed"
                        />
                    </div>
                    <div className="flex flex-col items-center mt-20">
                        <h4 className="text-3xl text-blue-500">
                            Do Xuan Trung
                        </h4>
                        <p className="my-5 text-center max-w-md lg:">
                            Every utility class in Tailwind can be applied
                            conditionally by adding a modifier to the beginning
                            of the class name that describes the condition you
                            want to target.
                        </p>
                        <div className="flex flex-row gap-10">
                            <BsGithub size={50} />
                            <AiFillGitlab size={50} />
                            <BsLinkedin size={50} />
                        </div>
                    </div>
                </section>
            </div>
        );
    };

    const renderFooter = () => {
        return (
            <div>
                <div className="flex flex-row mt-20 gap-10">
                    <Image
                        src={require("../../public/images/web1.png")}
                        className="w-1/2"
                    />
                    <Image
                        src={require("../../public/images/web1.png")}
                        className="w-1/2"
                    />
                </div>
            </div>
        );
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Do Xuan Trung</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="px-5 overflow-y-scroll">
                {renderHeader()}
                {renderBody()}
                {renderFooter()}
            </main>

            {/* <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer> */}
        </div>
    );
};

export default Home;
